global:
  enabled: false
  enableConsulNamespaces: true
  image: hashicorp/consul-enterprise:1.11.0-ent-alpha
  adminPartitions:
    enabled: true
    name: "blue"
  tls:
    enabled: true
#    enableAutoEncrypt: true
    caCert:
      secretName: servers-consul-ca-cert
      secretKey: tls.crt
    caKey:
      secretName: servers-consul-ca-key
      secretKey: tls.key
#  acls:
#    manageSystemACLs: true
#    bootstrapToken:
#      secretName: servers-consul-partitions-acl-token
#      secretKey: token
server:
  enterpriseLicense:
    secretName: license
    secretKey: key
externalServers:
  enabled: true
  hosts: [ "35.192.119.38" ]
  tlsServerName: server.dc1.consul
#  k8sAuthMethodHost: https://34.121.209.52
client:
  enabled: true
  exposeGossipPorts: true
  join: [ "35.192.119.38" ]
connectInject:
  enabled: true
  consulNamespaces:
    mirroringK8S: true
controller:
  enabled: true